### PR TITLE
Fix 'save instance state' functionality

### LINKED ISSUE #28: Child state saving issues
Hello Zach! 👋 

I was playing around with this library yesterday in my app and I ran into a couple issues with your `ChildSavedStateRegistry` composable function. I think I've solved one of the issues, but I need help with the other. 

The first issue was that child values weren't restored across process recreation. There's a [rememberSavedInstanceState](https://github.com/zach-klippenstein/compose-backstack/blob/master/compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt#L23) call with a mutable map, but that map never gets mutated (and so the values never get saved). I think the fix is as straightforward as [this](https://github.com/zach-klippenstein/compose-backstack/compare/master...grandstaish:brad/fix-child-ss). 

With the first fix applied, child restoration is mostly working. The one (major) exception is that the _currently_ visible child doesn't get saved/restored. The reason being that we only ever call `performSave()` for offscreen children. And compose doesn't do any magic to propagate save calls down to child registries. I haven't yet been able to solve this one.

### PR DESCRIPTION
**Pull request by grandstaish**
Fixes #28 

Most of this functionality is borrowed directly from how `rememberSavedInstanceState` works. Each screen now registers its own provider with its parent `UiSavedStateRegistry`. This means when compose-provided (topmost) registry saves, all of our child registries recursively save too. The rest of the implementation is identical, we still trigger save when a screen transitions offscreen, and restore that state when a screen comes back onscreen. 

Happy to make any changes/improvements!

### CODE REVIEW

File: buildSrc/src/main/resources/versions.properties [hunk 1]
```diff
@@ -1,6 +1,6 @@
 # -SNAPSHOT will automatically be appended. Pass -PisRelease=true to gradlew to release.
 releaseVersion=0.4.0
 
-androidGradlePluginVersion=4.1.0-alpha06
+androidGradlePluginVersion=4.1.0-alpha08
```
Comment (zach-klippenstein) [inline buildSrc/src/main/resources/versions.properties:4]: This should be the latest 4.2 alpha now.

File: compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt [hunk 2]
```diff
@@ -1,69 +1,91 @@
...
 }
 
-internal class SavedStateHolder(
-    private val canBeSaved: (Any) -> Boolean,
-    private var values: Map<String, Any>
-) {
-    var registry: UiSavedStateRegistry = createRegistry()
-        private set
+internal class SavedStateHolder : CompositionLifecycleObserver {
+    private var key: String? = null
```
Comment (zach-klippenstein) [inline compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt]: Please add kdoc describing what this property is used for.

File: compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt [hunk 3]
```diff
@@ -1,69 +1,91 @@
...
+    private var parent: UiSavedStateRegistry? = null
     private var isScreenVisible = false
+    private var value: Map<String, Any>? = null
```
Comment (zach-klippenstein) [inline compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt]: Nit: name this `values` since it holds more than one?

File: compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt [hunk 4]
```diff
@@ -1,69 +1,91 @@
...
      */
-    fun setScreenVisibility(isVisible: Boolean) {
-        if (isVisible == this.isScreenVisible) return
+    @Suppress("UNCHECKED_CAST")
+    fun updateAndReturnRegistry(
+        key: String,
+        parent: UiSavedStateRegistry?,
+        isVisible: Boolean
+    ): UiSavedStateRegistry {
+        value = value ?: parent?.consumeRestored(key) as Map<String, Any>? ?: mapOf()
```
Comment (zach-klippenstein) [inline compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt]: Should be `emptyMap()`

Comment (zach-klippenstein) [reply compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt]: Please add a comment here explaining why the resolution order is the way it is.

File: compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt [hunk 5]
```diff
@@ -1,69 +1,91 @@
...
+
+        val oldRegistry = this.parent
```
Comment (zach-klippenstein) [inline compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt]: Nit: name this `oldParent` to be consistent

File: compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt [hunk 6]
```diff
@@ -1,69 +1,91 @@
...
+        val oldKey = this.key
+        this.parent = parent
+        this.key = key
+
+        if (oldRegistry !== registry || oldKey != key) {
```
Comment (zach-klippenstein) [inline compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt]: Is the identity comparison for registries required? This is subtle and easy to miss, please add a comment.

File: compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt [hunk 7]
```diff
@@ -1,69 +1,91 @@
...
+            oldRegistry?.unregisterProvider(oldKey!!)
```
Comment (zach-klippenstein) [inline compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt]: Not clear that `oldKey` will always be non-null here. Can you write this code in a way that makes the double bang unnecessary? Or at least add a comment explaining why it's valid?

Eg: `oldKey?.let { oldRegistry?.unregister(it) }`

File: compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt [hunk 8]
```diff
@@ -1,69 +1,91 @@
...
             // The UiSavedStateRegistry function makes a defensive copy of the passed-in map, so
             // it needs to be recreated on every restoration.
             registry = createRegistry()
         }
+
+        return registry
+    }
+
+    override fun onLeave() {
+        parent?.unregisterProvider(key!!)
```
Comment (zach-klippenstein) [inline compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt]: Same issue with nullability here.

File: compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt [hunk 9]
```diff
@@ -1,69 +1,91 @@
...
+    }
+
+    override fun onEnter() {
```
Comment (zach-klippenstein) [inline compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt:79]: Nit: Put this before onLeave, since it is the lifecycle method that gets called first.

File: compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt (hunk 2 above)
Comment (zach-klippenstein) [reply compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt]: Actually, I'm pretty sure this can be passed into the constructor and will never change. That would simplify this code a bit and remove the null assertions below.

File: compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt (hunk 7 above)
Comment (zach-klippenstein) [reply compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt]: Unnecessary if you make key a non-nullable constructor val.

File: compose-backstack/src/test/java/com/zachklipp/compose/backstack/SavedStateHolderTest.kt [hunk 10]
```diff
@@ -1,56 +1,130 @@
...
+    }
+
+    @Test
+    fun `cleans up restored values from previous save`() {
+        val restoredValues = mutableMapOf("pk" to mapOf("old key" to "old value"))
+        val parent = UiSavedStateRegistry(restoredValues = restoredValues, canBeSaved = { true })
+        val holder = SavedStateHolder()
+
+        var registry = holder.updateAndReturnRegistry(key = "pk", parent = parent, isVisible = true)
+        // Consume the old key.
```
Comment (zach-klippenstein) [inline compose-backstack/src/test/java/com/zachklipp/compose/backstack/SavedStateHolderTest.kt]: Nit: unnecessary comment

**Review by zach-klippenstein — CHANGES_REQUESTED** [review]
These tests are great! Left a few comments but overall this makes a lot of sense. Thanks!

File: compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt (hunk 2 above)
Comment (grandstaish) [reply compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt]: Yeah I think you're right, it differs from `rememberSavedInstanceState` because that function allows for custom keys.

File: compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt (hunk 6 above)
Comment (grandstaish) [reply compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt:49]: No it doesn't look like it, but they're doing an identity comparison in `rememberSavedInstanceState`

File: buildSrc/src/main/resources/versions.properties (hunk 1 above)
Comment (grandstaish) [reply buildSrc/src/main/resources/versions.properties:4]: I tried this, but it required a newer version of Gradle, and that didn't play nice with compose.

Comment (zach-klippenstein) [reply buildSrc/src/main/resources/versions.properties:4]: Oh that's unfortunate. I could have sworn I'd had this working in a different codebase at some point, but this isn't really in scope for this PR anyway so this is fine.

File: compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt (hunk 6 above)
Comment (zach-klippenstein) [reply compose-backstack/src/main/java/com/zachklipp/compose/backstack/ChildSavedStateRegistry.kt]: This comment is really helpful, thanks!

**Review by zach-klippenstein — APPROVED** [review]
This looks great. Please squash your commits, then I will merge.

**Comment by zach-klippenstein** [comment]
Oops, should have merged this before deleting the old `master` branch, sorry.

**Comment by zach-klippenstein** [comment]
Sorry it took me so long to merge this, thanks! I'll do a release shortly.
